### ISSUE TITLE
Critical: websocket block

### ISSUE THREAD

**Issue by lroffia** [arces-wot/SEPA#16]
```2017-07-23 19:33:36,313 (WebsocketServer.java:69) [DEBUG] @onClose
Uncaught exception in thread "WebSocketWorker-16":java.lang.OutOfMemoryError: Java heap space
        at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
        at java.util.HashMap.putVal(HashMap.java:630)
        at java.util.HashMap.put(HashMap.java:611)
        at sun.util.resources.OpenListResourceBundle.loadLookup(OpenListResourceBundle.java:146)
        at sun.util.resources.OpenListResourceBundle.loadLookupTablesIfNecessary(OpenListResourceBundle.java:128)
        at sun.util.resources.OpenListResourceBundle.handleKeySet(OpenListResourceBundle.java:96)
        at java.util.ResourceBundle.containsKey(ResourceBundle.java:1807)
        at sun.util.locale.provider.LocaleResources.getTimeZoneNames(LocaleResources.java:263)
        at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayNameArray(TimeZoneNameProviderImpl.java:124)2017-07-23 19:33:39,098 (KeepAlive.java:79) [DEBUG] @unsubscribeAll
2017-07-23 19:33:39,101 (TokenHandler.java:80) [DEBUG] Get token #254 (Available: 982)

        at sun.util.locale.provider.TimeZoneNameProviderImpl.getDisplayName(TimeZoneNameProviderImpl.java:99)
        at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getName(TimeZoneNameUtility.java:240)2017-07-23 19:33:39,101 (KeepAlive.java:91) [DEBUG] >> Scheduling UNSUBSCRIBE request #254

2017-07-23 19:33:39,308 (RequestResponseHandler.java:124) [DEBUG] >> UNSUBSCRIBE #254 sepa://subscription/cea0cd5e-e165-4c33-b46f-8bb2031a9aa5
        at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:198)2017-07-23 19:33:39,309 (Scheduler.java:146) [DEBUG] >> UNSUBSCRIBE #254 sepa://subscription/cea0cd5e-e165-4c33-b46f-8bb2031a9aa5

2017-07-23 19:33:39,309 (Processor.java:95) [DEBUG] *Process* UNSUBSCRIBE #254 sepa://subscription/cea0cd5e-e165-4c33-b46f-8bb2031a9aa5
        at sun.util.locale.provider.TimeZoneNameUtility$TimeZoneNameGetter.getObject(TimeZoneNameUtility.java:184)2017-07-23 19:33:39,309 (SPUManager.java:64) [DEBUG] Process UNSUBSCRIBE #254

2017-07-23 19:33:39,309 (Processor.java:102) [DEBUG] << {"unsubscribed":"sepa://subscription/cea0cd5e-e165-4c33-b46f-8bb2031a9aa5"}
        at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:281)2017-07-23 19:33:39,310 (RequestResponseHandler.java:80) [DEBUG] << {"unsubscribed":"sepa://subscription/cea0cd5e-e165-4c33-b46f-8bb2031a9aa5"}

2017-07-23 19:33:39,310 (Scheduler.java:198) [DEBUG] << UNSUBSCRIBE RESPONSE #254 {"unsubscribed":"sepa://subscription/cea0cd5e-e165-4c33-b46f-8bb2031a9aa5"}
        at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:265)2017-07-23 19:33:39,310 (RequestResponseHandler.java:248) [DEBUG] Waiting for UNSUBSCRIBE requests...

        at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayNamesImpl(TimeZoneNameUtility.java:166)
        at sun.util.locale.provider.TimeZoneNameUtility.retrieveDisplayName(TimeZoneNameUtility.java:137)
        at java.util.TimeZone.getDisplayName(TimeZone.java:400)
        at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1271)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:966)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
        at java.text.DateFormat.format(DateFormat.java:345)
        at org.java_websocket.drafts.Draft_6455.getServerTime(Draft_6455.java:38)
        at org.java_websocket.drafts.Draft_6455.postProcessHandshakeResponseAsServer(Draft_6455.java:24)
        at org.java_websocket.WebSocketImpl.decodeHandshake(WebSocketImpl.java:250)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:173)
        at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:781)```

**Comment by lroffia** [comment]
2017-08-01 15:32:05,971 (SPU.java:110) [DEBUG] sepa://subscription/5ae194e2-3810-4fc1-8cf6-0a616f5014ad Entering main loop...
2017-08-01 15:32:05,971 (SPU.java:94) [DEBUG] sepa://subscription/5ae194e2-3810-4fc1-8cf6-0a616f5014ad Waiting new update response...                                                                       2017-08-01 15:33:10,533 (WebsocketServer.java:69) [DEBUG] @onClose                                                                                                                                          Uncaught exception in thread "WebSocketWorker-19":2017-08-01 15:33:13,555 (KeepAlive.java:79) [DEBUG] @unsubscribeAll                                                                                       java.lang.OutOfMemoryError: Java heap space                                                                                                                                                                 2017-08-01 15:33:13,556 (TokenHandler.java:80) [DEBUG] Get token #230 (Available
