### ISSUE TITLE
Blazegraph out of memory

### ISSUE THREAD

**Issue by lroffia** [arces-wot/SEPA#20]
```
5259008 [Friday, September 29, 2017 2:27:39 PM UTC], commitCounter=1559918, commitRecordAddr={off=NATIVE:-3945402,len=422}, commitRecordIndexAddr={off=NATIVE:-8398,len=220}, blockSequence=2, quorumToken=-1, metaBitsAddr=60112764984, metaStartAddr=23836, storeType=RW, uuid=fd5915a5-0498-4a65-b30e-d47583c9fc2a, offsetBits=42, checksum=789653958, createTime=1506351399782 [Monday, September 25, 2017 2:56:39 PM UTC], closeTime=0}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlUpdateTask.call(QueryServlet.java:552)
        at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlUpdateTask.call(QueryServlet.java:460)
        at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
Caused by: org.openrdf.query.UpdateExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not commit index: name=kb.spo.SPOC: lastRootBlock=rootBlock{ rootBlock=0, challisField=1559918, version=3, nextOffset=88965952577743, localTime=1506695260175 [Friday, September 29, 2017 2:27:40 PM UTC], firstCommitTime=1506351400906 [Monday, September 25, 2017 2:56:40 PM UTC], lastCommitTime=1506695259008 [Friday, September 29, 2017 2:27:39 PM UTC], commitCounter=1559918, commitRecordAddr={off=NATIVE:-3945402,len=422}, commitRecordIndexAddr={off=NATIVE:-8398,len=220}, blockSequence=2, quorumToken=-1, metaBitsAddr=60112764984, metaStartAddr=23836, storeType=RW, uuid=fd5915a5-0498-4a65-b30e-d47583c9fc2a, offsetBits=42, checksum=789653958, createTime=1506351399782 [Monday, September 25, 2017 2:56:39 PM UTC], closeTime=0}
        at com.bigdata.rdf.sparql.ast.eval.ASTEvalHelper.executeUpdate(ASTEvalHelper.java:1080)
        at com.bigdata.rdf.sail.BigdataSailUpdate.execute2(BigdataSailUpdate.java:152)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$UpdateTask.doQuery(BigdataRDFContext.java:1934)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.innerCall(BigdataRDFContext.java:1536)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:1501)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:714)
        ... 4 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not commit index: name=kb.spo.SPOC: lastRootBlock=rootBlock{ rootBlock=0, challisField=1559918, version=3, nextOffset=88965952577743, localTime=1506695260175 [Friday, September 29, 2017 2:27:40 PM UTC], firstCommitTime=1506351400906 [Monday, September 25, 2017 2:56:40 PM UTC], lastCommitTime=1506695259008 [Friday, September 29, 2017 2:27:39 PM UTC], commitCounter=1559918, commitRecordAddr={off=NATIVE:-3945402,len=422}, commitRecordIndexAddr={off=NATIVE:-8398,len=220}, blockSequence=2, quorumToken=-1, metaBitsAddr=60112764984, metaStartAddr=23836, storeType=RW, uuid=fd5915a5-0498-4a65-b30e-d47583c9fc2a, offsetBits=42, checksum=789653958, createTime=1506351399782 [Monday, September 25, 2017 2:56:39 PM UTC], closeTime=0}
        at com.bigdata.journal.AbstractJournal.commit(AbstractJournal.java:3131)
        at com.bigdata.rdf.store.LocalTripleStore.commit(LocalTripleStore.java:98)
        at com.bigdata.rdf.sail.BigdataSail$BigdataSailConnection.commit2(BigdataSail.java:3695)
        at com.bigdata.rdf.sail.BigdataSailRepositoryConnection.commit2(BigdataSailRepositoryConnection.java:330)
        at com.bigdata.rdf.sparql.ast.eval.AST2BOpUpdate.convertCommit(AST2BOpUpdate.java:375)
        at com.bigdata.rdf.sparql.ast.eval.AST2BOpUpdate.convertUpdate(AST2BOpUpdate.java:321)
        at com.bigdata.rdf.sparql.ast.eval.ASTEvalHelper.executeUpdate(ASTEvalHelper.java:1072)
        ... 9 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not commit index: name=kb.spo.SPOC
        at com.bigdata.journal.Name2Addr.handleCommit(Name2Addr.java:859)
        at com.bigdata.journal.AbstractJournal.notifyCommitters(AbstractJournal.java:2716)
        at com.bigdata.journal.AbstractJournal.access$1700(AbstractJournal.java:255)
        at com.bigdata.journal.AbstractJournal$CommitState.notifyCommitters(AbstractJournal.java:3422)
        at com.bigdata.journal.AbstractJournal$CommitState.access$2600(AbstractJournal.java:3298)
        at com.bigdata.journal.AbstractJournal.commitNow(AbstractJournal.java:4092)
        at com.bigdata.journal.AbstractJournal.commit(AbstractJournal.java:3129)
        ... 15 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Could not commit index: name=kb.spo.SPOC
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.bigdata.journal.Name2Addr.handleCommit(Name2Addr.java:749)
        ... 21 more
Caused by: java.lang.RuntimeException: Could not commit index: name=kb.spo.SPOC
        at com.bigdata.journal.Name2Addr$CommitIndexTask.call(Name2Addr.java:578)
        at com.bigdata.journal.Name2Addr$CommitIndexTask.call(Name2Addr.java:513)
        ... 4 more
Caused by: java.lang.OutOfMemoryError: Java heap space
WARN : QueuedThreadPool.java:591: 
ERROR: Banner.java:160: Uncaught exception in thread
java.lang.OutOfMemoryError: Java heap space
ERROR: Banner.java:160: Uncaught exception in thread
java.lang.OutOfMemoryError: Java heap space
WARN : ServletHandler.java:665: Error for /blazegraph/namespace/kb/sparql
java.lang.OutOfMemoryError: Java heap space
Killed

```

**Comment by lroffia** [comment]
'''        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.openrdf.query.TupleQueryResultHandlerException: org.eclipse.jetty.io.EofException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:864)
        at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:670)
        at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:68)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
Caused by: org.openrdf.query.TupleQueryResultHandlerException: org.eclipse.jetty.io.EofException
        at com.bigdata.rdf.rio.json.SPARQLJSONWriterBase.endQueryResult(SPARQLJSONWriterBase.java:238)
        at com.bigdata.rdf.rio.json.BigdataSPARQLResultsJSONWriter.endQueryResult(BigdataSPARQLResultsJSONWriter.java:36)
        at org.openrdf.query.QueryResults.report(QueryResults.java:163)
        at org.openrdf.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:76)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$TupleQueryTask.doQuery(BigdataRDFContext.java:1713)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.innerCall(BigdataRDFContext.java:1569)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:1534)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:747)
        ... 4 more
Caused by: org.eclipse.jetty.io.EofException
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:337)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:128)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:646)
        at org.eclipse.jetty.util.IteratingCallback.processIterations(IteratingCallback.java:233)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:193)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:457)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:769)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:802)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:139)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:132)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:234)
        at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
        at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
        at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.flush(WriterBasedJsonGenerator.java:860)
        at com.bigdata.rdf.rio.json.SPARQLJSONWriterBase.endDocument(SPARQLJSONWriterBase.java:435)
        at com.bigdata.rdf.rio.json.BigdataSPARQLResultsJSONWriter.endDocument(BigdataSPARQLResultsJSONWriter.java:36)
        at com.bigdata.rdf.rio.json.SPARQLJSONWriterBase.endQueryResult(SPARQLJSONWriterBase.java:235)
        ... 11 more
Caused by: java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
        at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.write(IOUtil.java:148)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172)'''

**Comment by relu91** [comment]
About the last exception it seems that blazegraph  was attempting to write a query result but the socket was closed. My guess is that or SEPA closed too early the socket or there was some unlucky connection issue between the accept of the request and the response.  

In any case I think it should be reported to blazegraph, the database should be resilient to this kind of events.

**Comment by relu91** [comment]
Old issue, cannot be reproduced, closing...
