### ISSUE TITLE
Grizzly exception (Websocket)

### ISSUE THREAD

**Issue by lroffia** [arces-wot/SEPA#3]
Jun 06, 2017 3:50:06 PM org.glassfish.grizzly.filterchain.DefaultFilterChain execute
WARNING: GRIZZLY0013: Exception during FilterChain execution
java.lang.IllegalStateException: Unknown protocol MCTP/1.0
        at org.glassfish.grizzly.http.Protocol.valueOf(Protocol.java:111)
        at org.glassfish.grizzly.http.HttpHeader.getProtocol(HttpHeader.java:815)
        at org.glassfish.grizzly.http.HttpServerFilter.prepareResponse(HttpServerFilter.java:867)
        at org.glassfish.grizzly.http.HttpServerFilter.encodeHttpPacket(HttpServerFilter.java:834)
        at org.glassfish.grizzly.http.HttpServerFilter.commitAndCloseAsError(HttpServerFilter.java:1185)
        at org.glassfish.grizzly.http.HttpServerFilter.sendBadRequestResponse(HttpServerFilter.java:1177)
        at org.glassfish.grizzly.http.HttpServerFilter.onHttpHeaderError(HttpServerFilter.java:796)
        at org.glassfish.grizzly.http.HttpCodecFilter.handleRead(HttpCodecFilter.java:583)
        at org.glassfish.grizzly.http.HttpServerFilter.handleRead(HttpServerFilter.java:334)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.SameThreadIOStrategy.executeIoEvent(SameThreadIOStrategy.java:103)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:89)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:415)
        at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:384)
        at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:348)
        at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:279)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        at java.lang.Thread.run(Thread.java:745)

**Comment by lroffia** [comment]
grizzly not used anymore
